apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gjxf8shc6-python 
  janus-idp.io/tekton: gjxf8shc6-python
  backstage.io/kubernetes-id: gjxf8shc6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gjxf8shc6-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  